#!/bin/bash -e

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru

source ${SOURCE_DIR}/base/rc/config

apt-get update
apt-get install -y wget maven tomcat7

#Install Java 8
mkdir /opt/java && cd /opt/java
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.tar.gz"
tar -zxvf jdk-8u45-linux-x64.tar.gz
rm -rf jdk-8u45-linux-x64.tar.gz
cd jdk1.8.0_45 

echo 'export JAVA_HOME="/opt/java/jdk1.8.0_45"' >> /etc/profile
echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> /etc/profile
source /etc/profile

cp $SOURCE_DIR/java/Procfile $SOURCE_DIR/default/Procfile
rm -rf /var/lib/tomcat7/webapps
ln -s ${CURRENT_DIR} /var/lib/tomcat7/webapps
mkdir -p /usr/share/tomcat7/common/classes /usr/share/tomcat7/server/classes /usr/share/tomcat7/shared/classes
chown -R ${USER}:${USER} /etc/tomcat7 /var/lib/tomcat7 /var/cache/tomcat7 /var/log/tomcat7 /usr/share/tomcat7
sed -i 's/8080/8888/' /etc/tomcat7/server.xml
